//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group1_Project_ASPNET_Travel_Booking
{


    public partial class Default
    {

        /// <summary>
        /// btnHeroBook control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnHeroBook;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Group1_Project_ASPNET_Travel_Booking.Site1 Master
        {
            get
            {
                return ((Group1_Project_ASPNET_Travel_Booking.Site1)(base.Master));
            }
        }
    }
}
